"""initial_schema

Revision ID: 3b7377bff1e1
Revises: 
Create Date: 2026-06-20 05:28:40.607295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b7377bff1e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anime_list',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('poster_id', sa.String(length=255), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('languages', postgresql.ARRAY(sa.String()), server_default=sa.text('ARRAY[]::varchar[]'), nullable=False),
    sa.Column('rating_sum', sa.Numeric(precision=10, scale=2), server_default='0', nullable=False),
    sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('views_week', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('anime_id')
    )
    op.create_index(op.f('ix_anime_list_title'), 'anime_list', ['title'], unique=False)
    op.create_index(op.f('ix_anime_list_views_week'), 'anime_list', ['views_week'], unique=False)
    op.create_index(op.f('ix_anime_list_year'), 'anime_list', ['year'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_index('idx_channel_active', 'channels', ['is_active'], unique=False)
    op.create_table('genres',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_genres_name'), 'genres', ['name'], unique=True)
    op.create_table('outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aggregate', sa.String(length=255), nullable=False),
    sa.Column('aggregate_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('event_hash', sa.String(length=64), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_outbox_processing', 'outbox_events', ['processed', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate'), 'outbox_events', ['aggregate'], unique=False)
    op.create_index(op.f('ix_outbox_events_aggregate_id'), 'outbox_events', ['aggregate_id'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_hash'), 'outbox_events', ['event_hash'], unique=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('points', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.Enum('USER', 'VIP', 'ADMIN', name='user_status'), nullable=False),
    sa.Column('vip_expire_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sleep_reminder_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index('idx_user_status_points', 'users', ['status', 'points'], unique=False)
    op.create_index(op.f('ix_users_joined_at'), 'users', ['joined_at'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('anime_episodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('episode', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime_list.anime_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('anime_id', 'episode')
    )
    op.create_index(op.f('ix_anime_episodes_anime_id'), 'anime_episodes', ['anime_id'], unique=False)
    op.create_index(op.f('ix_anime_episodes_episode'), 'anime_episodes', ['episode'], unique=False)
    op.create_table('anime_genres',
    sa.Column('anime_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['anime_id'], ['anime_list.anime_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('anime_id', 'genre_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anime_genres')
    op.drop_index(op.f('ix_anime_episodes_episode'), table_name='anime_episodes')
    op.drop_index(op.f('ix_anime_episodes_anime_id'), table_name='anime_episodes')
    op.drop_table('anime_episodes')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_joined_at'), table_name='users')
    op.drop_index('idx_user_status_points', table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_event_hash'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate_id'), table_name='outbox_events')
    op.drop_index(op.f('ix_outbox_events_aggregate'), table_name='outbox_events')
    op.drop_index('idx_outbox_processing', table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_genres_name'), table_name='genres')
    op.drop_table('genres')
    op.drop_index('idx_channel_active', table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_anime_list_year'), table_name='anime_list')
    op.drop_index(op.f('ix_anime_list_views_week'), table_name='anime_list')
    op.drop_index(op.f('ix_anime_list_title'), table_name='anime_list')
    op.drop_table('anime_list')
    # ### end Alembic commands ###
